<?php
require_once __DIR__ . '/../src/layout.php'; require_auth(); $pdo=db();
if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check();$id=(int)($_POST['id']??0);$vals=[trim($_POST['name']??''),trim($_POST['document']??''),trim($_POST['phone']??''),trim($_POST['email']??''),trim($_POST['address']??''),$_POST['status']??'ativo',(float)str_replace(',','.',$_POST['standard_km']??0),isset($_POST['has_contract'])?1:0,(float)str_replace(',','.',$_POST['monthly_fee']??0),(float)str_replace(',','.',$_POST['extra_visit_fee']??0),(int)($_POST['due_day']??20),trim($_POST['contract_notes']??''),trim($_POST['notes']??'')];if($id){$st=$pdo->prepare('UPDATE clients SET name=?,document=?,phone=?,email=?,address=?,status=?,standard_km=?,has_contract=?,monthly_fee=?,extra_visit_fee=?,due_day=?,contract_notes=?,notes=? WHERE id=?');$st->execute([...$vals,$id]);flash('success','Cliente atualizado.');}else{$st=$pdo->prepare('INSERT INTO clients(name,document,phone,email,address,status,standard_km,has_contract,monthly_fee,extra_visit_fee,due_day,contract_notes,notes) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)');$st->execute($vals);flash('success','Cliente cadastrado.');}redirect(base_url('clients.php'));}
if(isset($_GET['delete'])){if(!role_allowed(['admin'])) exit('Acesso negado');$st=$pdo->prepare('UPDATE clients SET deleted_at=NOW() WHERE id=?');$st->execute([(int)$_GET['delete']]);flash('warning','Cliente inativado logicamente.');redirect(base_url('clients.php'));}
$edit=null;if(isset($_GET['edit'])){$st=$pdo->prepare('SELECT * FROM clients WHERE id=?');$st->execute([(int)$_GET['edit']]);$edit=$st->fetch();}
$q=trim($_GET['q']??'');$status=$_GET['status']??'';$sql='SELECT * FROM clients WHERE deleted_at IS NULL';$args=[];if($q!==''){$sql.=' AND (name LIKE ? OR document LIKE ?)';$args[]="%$q%";$args[]="%$q%";}if(in_array($status,['ativo','inativo'],true)){$sql.=' AND status=?';$args[]=$status;}$sql.=' ORDER BY name';$st=$pdo->prepare($sql);$st->execute($args);$rows=$st->fetchAll();render_header('Clientes');
?>
<div class="row g-3"><div class="col-lg-4"><div class="card"><div class="card-body"><h5><?=$edit?'Editar':'Novo'?> cliente</h5><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=e((string)($edit['id']??''))?>"><?php foreach([['name','Nome/Razão Social'],['document','CPF/CNPJ'],['phone','Telefone'],['email','E-mail'],['address','Endereço Completo']] as [$n,$l]):?><div class="mb-2"><label class="form-label"><?=$l?></label><input class="form-control" name="<?=$n?>" value="<?=e($edit[$n]??'')?>" <?=$n==='name'?'required':''?>></div><?php endforeach;?><div class="row"><div class="col"><label>Status</label><select class="form-select" name="status"><option value="ativo">Ativo</option><option value="inativo" <?=($edit['status']??'')==='inativo'?'selected':''?>>Inativo</option></select></div><div class="col"><label>KM padrão</label><input class="form-control" name="standard_km" value="<?=e((string)($edit['standard_km']??0))?>"></div></div><div class="form-check my-3"><input class="form-check-input" type="checkbox" name="has_contract" id="hc" <?=!empty($edit['has_contract'])?'checked':''?>><label class="form-check-label" for="hc">Possui contrato</label></div><div class="row"><div class="col"><label>Mensalidade</label><input class="form-control" name="monthly_fee" value="<?=e((string)($edit['monthly_fee']??0))?>"></div><div class="col"><label>Visita adicional</label><input class="form-control" name="extra_visit_fee" value="<?=e((string)($edit['extra_visit_fee']??0))?>"></div></div><div class="mb-2"><label>Dia vencimento</label><input class="form-control" type="number" min="1" max="28" name="due_day" value="<?=e((string)($edit['due_day']??20))?>"></div><div class="mb-2"><label>Observações contrato</label><textarea class="form-control" name="contract_notes"><?=e($edit['contract_notes']??'')?></textarea></div><div class="mb-3"><label>Observações gerais</label><textarea class="form-control" name="notes"><?=e($edit['notes']??'')?></textarea></div><button class="btn btn-primary">Salvar</button></form></div></div></div>
<div class="col-lg-8"><form class="row g-2 mb-2"><div class="col"><input class="form-control" name="q" placeholder="Pesquisar nome ou CPF/CNPJ" value="<?=e($q)?>"></div><div class="col-auto"><select class="form-select" name="status"><option value="">Todos status</option><option value="ativo" <?=$status==='ativo'?'selected':''?>>Ativo</option><option value="inativo" <?=$status==='inativo'?'selected':''?>>Inativo</option></select></div><div class="col-auto"><button class="btn btn-outline-primary">Filtrar</button></div></form><div class="table-wrap"><div class="table-responsive"><table class="table"><thead><tr><th>Cliente</th><th>Documento</th><th>Status</th><th>Contrato</th><th>Mensalidade</th><th></th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e($r['name'])?></td><td><?=e($r['document'])?></td><td><?=e($r['status'])?></td><td><?=$r['has_contract']?'Sim':'Não'?></td><td><?=money($r['monthly_fee'])?></td><td class="text-nowrap"><a class="btn btn-sm btn-outline-primary" href="?edit=<?=$r['id']?>">Editar</a> <a class="btn btn-sm btn-outline-danger" data-confirm="Excluir logicamente este cliente?" href="?delete=<?=$r['id']?>">Excluir</a></td></tr><?php endforeach;?></tbody></table></div></div></div></div>
<?php render_footer(); ?>
