<?php
require_once __DIR__ . '/../src/layout.php'; require_auth();$pdo=db();
function close_cycle(PDO $pdo,string $close): void {
    [$start,$end]=cycle_from_close_date($close);$competence=(new DateTimeImmutable($end))->format('Y-m');
    $clients=$pdo->query("SELECT * FROM clients WHERE deleted_at IS NULL AND status='ativo'")->fetchAll();
    foreach($clients as $c){
        $st=$pdo->prepare("SELECT t.*, (SELECT COALESCE(SUM(total_price),0) FROM ticket_materials tm WHERE tm.ticket_id=t.id) materials_total FROM tickets t WHERE t.client_id=? AND DATE(t.occurred_at) BETWEEN ? AND ? AND t.status IN ('solucionado','fechado') AND t.billed_at IS NULL ORDER BY t.occurred_at,t.id");$st->execute([$c['id'],$start,$end]);$tickets=$st->fetchAll();
        $monthly=$c['has_contract']?(float)$c['monthly_fee']:0;$services=0;$materials=0;$visits=0;$freeVisitUsed=false;
        foreach($tickets as $t){$services+=(float)$t['service_amount'];$materials+=(float)$t['materials_total'];if($c['has_contract'] && $t['service_type']==='presencial'){if(!$freeVisitUsed){$freeVisitUsed=true;}else{$visits+=(float)$c['extra_visit_fee'];}}}
        $prevSt=$pdo->prepare("SELECT COALESCE(SUM(total_amount-paid_amount),0) FROM receivables WHERE client_id=? AND status<>'pago' AND competence<>?");$prevSt->execute([$c['id'],$competence]);$previous=(float)$prevSt->fetchColumn();
        $advSt=$pdo->prepare("SELECT COALESCE(SUM(amount),0) FROM advances WHERE client_id=? AND consumed_at IS NULL AND advance_date<=?");$advSt->execute([$c['id'],$end]);$adv=(float)$advSt->fetchColumn();
        $disSt=$pdo->prepare("SELECT COALESCE(SUM(amount),0) FROM discounts WHERE client_id=? AND consumed_at IS NULL AND discount_date<=?");$disSt->execute([$c['id'],$end]);$dis=(float)$disSt->fetchColumn();
        $total=max(0,$monthly+$services+$materials+$visits+$previous-$adv-$dis);
        if($total<=0 && !$tickets && !$c['has_contract']) continue;
        $due=(new DateTimeImmutable($end))->setDate((int)substr($competence,0,4),(int)substr($competence,5,2),min((int)$c['due_day'],28))->format('Y-m-d');
        $pdo->beginTransaction();
        try{$st=$pdo->prepare("INSERT INTO receivables(client_id,competence,cycle_start,cycle_end,due_date,monthly_fee,services_amount,materials_amount,extra_visits_amount,discount_amount,advances_amount,previous_balance,total_amount) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE monthly_fee=VALUES(monthly_fee),services_amount=VALUES(services_amount),materials_amount=VALUES(materials_amount),extra_visits_amount=VALUES(extra_visits_amount),discount_amount=VALUES(discount_amount),advances_amount=VALUES(advances_amount),previous_balance=VALUES(previous_balance),total_amount=VALUES(total_amount)");$st->execute([$c['id'],$competence,$start,$end,$due,$monthly,$services,$materials,$visits,$dis,$adv,$previous,$total]);$st=$pdo->prepare('SELECT id FROM receivables WHERE client_id=? AND competence=?');$st->execute([$c['id'],$competence]);$rid=(int)$st->fetchColumn();if($tickets){$ids=array_column($tickets,'id');$in=implode(',',array_fill(0,count($ids),'?'));$st=$pdo->prepare("UPDATE tickets SET billed_at=NOW(),receivable_id=? WHERE id IN ($in)");$st->execute([$rid,...$ids]);}$pdo->prepare('UPDATE advances SET consumed_at=NOW(),receivable_id=? WHERE client_id=? AND consumed_at IS NULL AND advance_date<=?')->execute([$rid,$c['id'],$end]);$pdo->prepare('UPDATE discounts SET consumed_at=NOW(),receivable_id=? WHERE client_id=? AND consumed_at IS NULL AND discount_date<=?')->execute([$rid,$c['id'],$end]);$pdo->commit();}catch(Throwable $e){$pdo->rollBack();throw $e;}
    }
}
if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check();$action=$_POST['action']??'';if($action==='close'){close_cycle($pdo,$_POST['close_date']);flash('success','Ciclo fechado/recalculado.');}elseif($action==='pay'){$rid=(int)$_POST['receivable_id'];$amount=(float)str_replace(',','.',$_POST['amount']);$pdo->beginTransaction();$pdo->prepare('INSERT INTO payments(receivable_id,payment_date,amount,payment_method,notes) VALUES (?,?,?,?,?)')->execute([$rid,$_POST['payment_date'],$amount,$_POST['payment_method'],trim($_POST['notes']??'')]);$pdo->prepare('UPDATE receivables SET paid_amount=paid_amount+? WHERE id=?')->execute([$amount,$rid]);$pdo->prepare("UPDATE receivables SET status=CASE WHEN paid_amount>=total_amount THEN 'pago' WHEN paid_amount>0 THEN 'parcial' ELSE 'pendente' END WHERE id=?")->execute([$rid]);$pdo->commit();flash('success','Pagamento registrado.');}redirect(base_url('receivables.php'));}
$rows=$pdo->query("SELECT r.*,c.name client FROM receivables r JOIN clients c ON c.id=r.client_id ORDER BY competence DESC,c.name")->fetchAll();render_header('Contas a Receber');
?>
<div class="d-flex gap-2 justify-content-end mb-3"><form class="d-flex gap-2" method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="close"><input class="form-control" type="date" name="close_date" value="<?=date('Y-m-15')?>" required><button class="btn btn-primary" data-confirm="Fechar/recalcular este ciclo?">Fechar ciclo</button></form></div>
<div class="table-wrap"><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Cliente</th><th>Competência</th><th>Vencimento</th><th>Mensalidade</th><th>Serviços</th><th>Materiais</th><th>Visitas</th><th>Desconto</th><th>Anterior</th><th>Total</th><th>Pago</th><th>Saldo</th><th>Status</th><th>Pagamento</th></tr></thead><tbody><?php foreach($rows as $r):$saldo=(float)$r['total_amount']-(float)$r['paid_amount'];?><tr><td><?=e($r['client'])?></td><td><?=e($r['competence'])?></td><td><?=date('d/m/Y',strtotime($r['due_date']))?></td><td><?=money($r['monthly_fee'])?></td><td><?=money($r['services_amount'])?></td><td><?=money($r['materials_amount'])?></td><td><?=money($r['extra_visits_amount'])?></td><td><?=money($r['discount_amount'])?></td><td><?=money($r['previous_balance'])?></td><th><?=money($r['total_amount'])?></th><td><?=money($r['paid_amount'])?></td><td><?=money($saldo)?></td><td><?=e($r['status'])?></td><td><?php if($saldo>0):?><form method="post" class="d-flex gap-1"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="pay"><input type="hidden" name="receivable_id" value="<?=$r['id']?>"><input type="hidden" name="payment_date" value="<?=date('Y-m-d')?>"><input type="hidden" name="payment_method" value="pix"><input type="hidden" name="notes" value="Pagamento rápido"><input class="form-control form-control-sm" style="width:110px" name="amount" placeholder="Valor"><button class="btn btn-sm btn-success">R$</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></div>
<?php render_footer(); ?>
